/** Which dataset an analysis runs on. Demo and real data are never mixed. */
/**
 * Provenance label. Datasets are never mixed in any analysis.
 *  real — genuine, legitimately obtained observations (attested at import)
 *  demo — synthetic demonstration data generated by the app
 *  test — synthetic / fixture data used to test the pipeline
 */
export type Dataset = "real" | "demo" | "test";

export type ThresholdKey = "1.5x" | "2x" | "3x" | "5x" | "10x";

export interface Round {
  id: string;
  multiplier: number;
  round_time: string;
  source: string;
  dataset: Dataset;
  import_batch_id?: string | null;
  created_at: string;
}

export interface NewRound {
  multiplier: number;
  round_time: string;
  source: string;
  dataset: Dataset;
  import_batch_id?: string | null;
}

export type Confidence = "LOW" | "MEDIUM" | "HIGH";
export type PredictionResult = "pending" | "correct" | "incorrect";
export type Verdict = "edge_detected" | "no_edge" | "insufficient_data";

export interface Prediction {
  id: string;
  prediction_time: string;
  model_version: string;
  model_run_id: string | null;
  kind: "backtest" | "live";
  dataset: Dataset;
  based_on_round_time: string | null;
  probability_1_5x: number;
  probability_2x: number;
  probability_3x: number;
  probability_5x: number;
  probability_10x: number;
  baseline: Partial<Record<ThresholdKey, number>> | null;
  /** Exact model inputs (audit trail). Computed only from rounds before the target round. */
  features?: Record<string, number> | null;
  /** Last round the producing model was trained on. */
  train_end_round_time?: string | null;
  /** The round being predicted (set when known / resolved). */
  target_round_time?: string | null;
  /** Set when produced by a frozen validation-protocol run. */
  validation_run_id?: string | null;
  confidence: Confidence;
  predicted_class: string;
  actual_multiplier: number | null;
  result: PredictionResult;
  created_at: string;
}

export type NewPrediction = Omit<Prediction, "id" | "created_at">;

export interface ThresholdSelection {
  selected_model: string;
  validation_scores: Record<string, { brier: number; log_loss: number; roc_auc: number | null }>;
  beats_base_rate_on_validation: boolean;
}

export interface ModelRunReport {
  splits: Record<string, number | string>;
  selection: Record<string, ThresholdSelection>;
  metrics: Record<string, unknown>;
  feature_names: string[];
  signal?: import("@/lib/evaluation").SignalLevel;
}

export interface ModelRun {
  id: string;
  model_version: string;
  dataset: Dataset;
  training_samples: number;
  validation_samples: number;
  test_samples: number;
  accuracy: number | null;
  precision: number | null;
  recall: number | null;
  roc_auc: number | null;
  brier_score: number | null;
  baseline_accuracy: number | null;
  verdict: Verdict;
  confidence: Confidence;
  report: ModelRunReport;
  created_at: string;
}

export type NewModelRun = Omit<ModelRun, "id" | "created_at">;

export type SourceType = "manual" | "csv" | "api" | "live_feed" | "demo" | "test";

export interface DataSource {
  id: string;
  source_name: string;
  source_type: SourceType;
  enabled: boolean;
  last_update: string | null;
  notes: string | null;
  created_at: string;
}

export type CollectionMethod = "manual_record" | "official_export" | "authorized_api" | "synthetic" | "other";

export interface ImportBatch {
  id: string;
  dataset: Dataset;
  source_name: string;
  collection_method: CollectionMethod;
  provenance_notes: string;
  attested: boolean;
  file_name: string | null;
  file_sha256: string | null;
  rows_sha256: string | null;
  total_rows: number;
  valid_rows: number;
  rejected_rows: number;
  duplicates_in_file: number;
  already_stored: number;
  inserted_rows: number;
  first_round_time: string | null;
  last_round_time: string | null;
  collected_from: string | null;
  collected_to: string | null;
  quality_report: Record<string, unknown>;
  imported_at: string;
}

export type NewImportBatch = Omit<ImportBatch, "id" | "imported_at">;

export type ValidationStage = "final_test" | "confirmation";

export interface ValidationRun {
  id: string;
  dataset: Dataset;
  stage: ValidationStage;
  status: "registered" | "running" | "completed" | "failed";
  protocol_version: string;
  protocol_sha256: string;
  data_sha256: string;
  window_fingerprint: string;
  window_start: string;
  window_end: string;
  window_rounds: number;
  development_rounds: number;
  parent_run_id: string | null;
  job_id: string | null;
  result: Record<string, unknown> | null;
  classification: string | null;
  error: string | null;
  registered_at: string;
  completed_at: string | null;
}

export type NewValidationRun = Omit<ValidationRun, "id" | "registered_at" | "completed_at" | "result" | "classification" | "error" | "job_id"> &
  Partial<Pick<ValidationRun, "job_id">>;
