import { NextResponse, type NextRequest } from "next/server";
import { generateDemoRounds, DEMO_SOURCE } from "@/lib/demo";
import { guard, handler } from "@/lib/http";
import { ingestRounds } from "@/services/ingestion";
import { getRepository } from "@/services/repository";
import { canonicalRows, sha256Hex } from "@/lib/import/strict";

export const dynamic = "force-dynamic";

/** Load the synthetic DEMO dataset (is_demo = true). Never mixed with real data. */
export const POST = handler(async (req: NextRequest) => {
  await guard(req, { bucket: "demo", limit: 5, admin: true });
  const rows = generateDemoRounds();
  const repo = getRepository();
  const batch = await repo.insertImportBatch({
    dataset: "demo",
    source_name: DEMO_SOURCE,
    collection_method: "synthetic",
    provenance_notes: "DEMO DATA — NOT REAL GAME RESULTS. Generated by lib/demo.ts (i.i.d. draws, P(X ≥ m) ≈ 0.97/m, seed 20261004).",
    attested: false,
    file_name: null,
    file_sha256: null,
    rows_sha256: await sha256Hex(canonicalRows(rows)),
    total_rows: rows.length,
    valid_rows: rows.length,
    rejected_rows: 0,
    duplicates_in_file: 0,
    already_stored: 0,
    inserted_rows: 0,
    first_round_time: rows[0].round_time,
    last_round_time: rows[rows.length - 1].round_time,
    collected_from: null,
    collected_to: null,
    quality_report: {},
  });
  const result = await ingestRounds({ rows, source: DEMO_SOURCE, sourceType: "demo", dataset: "demo", autoPredict: false, importBatchId: batch.id });
  await repo.updateImportBatch(batch.id, { inserted_rows: result.inserted, already_stored: result.alreadyStored });
  const res = NextResponse.json({ ...result, label: "DEMO DATA — NOT REAL GAME RESULTS" });
  res.cookies.set("aal_dataset", "demo", { path: "/", sameSite: "lax", maxAge: 60 * 60 * 24 * 365 });
  return res;
});

/** Remove all demo rounds, demo model runs and demo predictions. */
export const DELETE = handler(async (req: NextRequest) => {
  await guard(req, { bucket: "demo", limit: 5, admin: true });
  const repo = getRepository();
  await repo.deletePredictions("demo");
  await repo.deleteModelRuns("demo");
  const deleted = await repo.deleteAllRounds("demo");
  await repo.deleteImportBatches("demo");
  return NextResponse.json({ deleted });
});
